# Generated by Django 5.2 on 2025-06-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
    ]
