# Generated by Django 5.2 on 2025-06-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_participant_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
